# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(db_index=True, default=False, help_text="Only assignments marked 'Active' will be shown to users. See <a href='/all-assignments.json' target='_blank'>all-assignments.json</a> for an unfiltered view containing expired and inactive assignments.")),
                ('description', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('expiration', models.DateTimeField(db_index=True, verbose_name='expiration date')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Assignments will be sorted from highest to lowest priority before being shown to users.  Assignments with the same priority will be sorted by expiration date.', validators=[django.core.validators.MaxValueValidator(100)])),
                ('require_call_first', models.BooleanField(default=False, help_text='If selected, the user will have to complete a call action for the current assignment before text actions become available.')),
            ],
            options={
                'ordering': ['-priority', 'expiration'],
            },
        ),
        migrations.CreateModel(
            name='CallAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('call_script', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('message_content', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='call_actions',
            field=models.ManyToManyField(blank=True, to='Transmission.CallAction'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='text_actions',
            field=models.ManyToManyField(blank=True, to='Transmission.TextAction'),
        ),
    ]
