# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('modelwithdates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transmission.ModelWithDates')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('Transmission.modelwithdates',),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('modelwithdates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transmission.ModelWithDates')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('expiration', models.DateTimeField(verbose_name='expiration date')),
                ('require_call_first', models.BooleanField(default=False)),
            ],
            bases=('Transmission.modelwithdates',),
        ),
        migrations.CreateModel(
            name='CallAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transmission.Action')),
                ('call_script', models.TextField(max_length=500)),
            ],
            bases=('Transmission.action',),
        ),
        migrations.CreateModel(
            name='TextAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transmission.Action')),
                ('message_content', models.TextField(max_length=200)),
            ],
            bases=('Transmission.action',),
        ),
        migrations.AddField(
            model_name='assignment',
            name='call_actions',
            field=models.ManyToManyField(blank=True, to='Transmission.CallAction'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='text_actions',
            field=models.ManyToManyField(blank=True, to='Transmission.TextAction'),
        ),
    ]
