# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='call_actions',
            field=models.ManyToManyField(blank=True, to='Transmission.CallAction'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text_actions',
            field=models.ManyToManyField(blank=True, to='Transmission.TextAction'),
        ),
    ]
