# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callaction',
            name='call_script',
            field=models.TextField(help_text="Call script will be evaluated as a <a href='https://mustache.github.io/mustache.5.html' target='_blank'>mustache template</a>.", max_length=500),
        ),
        migrations.AlterField(
            model_name='textaction',
            name='message_content',
            field=models.TextField(help_text="Message content will be evaluated as a <a href='https://mustache.github.io/mustache.5.html' target='_blank'>mustache template</a>.", max_length=200),
        ),
    ]
