# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Assignment order will be sorted from highest to lowest priority before being shown to users.'),
        ),
    ]
