# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transmission', '0002_auto_20161005_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callaction',
            name='call_script',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='textaction',
            name='message_content',
            field=models.TextField(max_length=200),
        ),
    ]
