# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 01:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transmission', '0002_assignment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=False, help_text='If deselected, this assignment will not be shown to users'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Assignments will be sorted from highest to lowest priority before being shown to users.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='require_call_first',
            field=models.BooleanField(default=False, help_text='If selected, the user will have to complete a call action for the current assignment before text actions become available.'),
        ),
    ]
