# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 02:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transmission', '0003_auto_20161009_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-priority', 'expiration']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(db_index=True, default=False, help_text="Only assignments marked 'Active' will be shown to users. See <a href='/all-assignments.json' target='_blank'>all-assignments.json</a> for an unfiltered view containing expired and inactive assignments."),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='expiration',
            field=models.DateTimeField(db_index=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Assignments will be sorted from highest to lowest priority before being shown to users.  Assignments with the same priority will be sorted by expiration date.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
